### ISSUE TITLE
Still not Real "Offline Lan"...

### ISSUE THREAD

**Issue by 0P3N50URC3-F0R3V3R** [Ododo/scc-lan-restore#13]
When i host without any internet connection, the LAN will not work... so this is not a real lan connection :\ Is there a way to fix that anyhow?
When i block these domains: 

lb-agora.ubisoft.com
secure.ubi.com
lb-lsg-prod.ubisoft.com
lb-rdv-as-prod01.ubisoft.com
ne1-z3-as-rdv03.ubisoft.com
static8.cdn.ubi.com

It still wont connect without internet... what if in the future these domains are gone? :D 
Everyone tells that this is lan fixed but the "matchmaking" lan not working real offline lan.
Is there any fox for this...?

**Comment by koteykaby** [comment]
I made some research on this issue, and my game isn't use these addresses when working on LAN. It works without internet connection. But I find that:

- The game sends some data to `lb-rdv-as-prod01.ubisoft.com` (SandboxUrl in MatchMakingConfig) with PRUDP, but doesn't receive any result:

![Image](https://github.com/user-attachments/assets/4de56b7d-7a9e-42f3-a56d-fa572386378d)

- The packet data is always the same, but sometimes first byte may be "3e" instead of "3f"

![Image](https://github.com/user-attachments/assets/10083780-0e8b-4d27-b6e6-fa95a6c665a8)

- I'm also tried to self-host this (and other) address from MatchMaking config, but LAN menu in the game is still worked, and data received only from SandboxUrl:

![Image](https://github.com/user-attachments/assets/8c2603b8-d930-4a54-a8af-d4c588e50e57)

Then I tried to remove all addresses from MatchMakingConfig xml:

![Image](https://github.com/user-attachments/assets/572d072b-d3e8-487c-a337-b81270115c54)

LAN menu still works without them, but if I will try to use "Find Match" button, it won't try to login to the official servers, but with those adresses in the MatchMakingConfig it will try (it doesn't make sense, servers are dead :D)

Can you please share Wireshark recording with packets that sends/comes from addresses that you're attached? It will help to understand your issue better.

**Comment by 0P3N50URC3-F0R3V3R** [comment]
I... cant use wireshark... i mean i never did before...  And yes it does work without internet  it( you can host the coop server), but you cannot find any matches on lan without the domains. enabled.. (Lan - > lobby screen searching)  If i enable the internet suddenly all will work well. On lan only, it wont find any games on the lan lobby.... (i yank out the wan cable from the router) and you can host, but you wont see each other in the list :\ 

I tested it i removed all domains as seen on your picture from the response, and if i do that, the game will stuck when you are press on the LAN button, and after a few seconds, it will simply say that the service is unavaliable... :\

**Comment by koteykaby** [comment]
> Watching your picture, yea... you are using some completely different py file than i have from this repo... and i dont receive packets like you do in the command prompt...

The command prompt screen is my own other UDP server that I wrote to view the adresses used by a game. For LAN menu fixing I`m still using scc-lan-restore script from the sources of this repo.

As for lobby discovering issue - it should be fixed in [this](https://github.com/barryZZJ/scc-lan-restore/tree/master) fork (according to [this PR](https://github.com/Ododo/scc-lan-restore/pull/12). Sometimes lobby packet may be broken and the peer won't see the lobby. This is the game netcode issue, unfortunately there's nothing we can do.

**Comment by 0P3N50URC3-F0R3V3R** [comment]
THx i checked it and it is working right when i add to the hosts file these: 
See each other and such... 

```
# Conviction
127.0.0.1 gconnect.ubi.com
127.0.0.1 lb-agora.ubisoft.com
127.0.0.1 secure.ubi.com
127.0.0.1 lb-lsg-prod.ubisoft.com
127.0.0.1 lb-rdv-as-prod01.ubisoft.com
127.0.0.1 ne1-z3-as-rdv03.ubisoft.com
127.0.0.1 static8.cdn.ubi.com
```

However... if i disable the internet its still wont work to see each other on the lan lobbies;  for some reason, but so far the hosts method did not worked either so, its a half-progress, but not ok entirely yet... Its not just sometimes broken btw :D its only broken when the internet is disabled-pulled out or firewalled (i tried everything)

**Comment by 0P3N50URC3-F0R3V3R** [comment]
OKAAAAY  Itested it, now if i dont have internet physicly pulled out from the router,
I can host, and i can see on the list the hosted party but when i try to connect to it: 

![Image](https://github.com/user-attachments/assets/5a244c02-a154-4027-a78a-2387616dcbfb)

**Comment by koteykaby** [comment]
Well, there's nothing to do without Wireshark recording. Only with it we can understand this problem better.

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Cmon... its not evident that anyone who have an issue with this, then everyone also using Wireshark... here is me... i used like fiddler before, but with wireshark i am unable to get relevant information or such... its just a big bowl of jibberish spaghetti information to me, and i dont know what and how to look... so if you wont give me an exact tutorial from that how to do it... or what to look for... it wont happen... 

Yesterday night i tried the physical disconnection with v3, and the internet and the lobby worked, i hosted and seen the lobby with the second client but when i try to connect to it, it just says that this is the result when i try to connect with no internet(only lan): 

![Image](https://github.com/user-attachments/assets/a071d55b-f41c-4750-ac72-a85c78c60d21)

So its an ALMOST good XD(also for some reason even if it works it shows 4 identical lobbies in every case...) I will try some more stuff... I haven ran out of ideas... :\
